version: '3'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: mysql
    ports:
      - "3306:3306"
    env_file:
      - .env